### PR TITLE
Only run GC 3 times instead of 4 to scrub

### PR DESCRIPTION
**Pull request by Zentrik**
Per [slack](https://julialang.slack.com/archives/C03A7RP2ZMW/p1700484605291009?thread_ts=1700475300.698339&cid=C03A7RP2ZMW), 'Diogo changed it so it only needs 3 to promote everything to old generation now'.

### CODE REVIEW

**Comment by Diogo-Netto** [comment]
Olá boa tarde eu não entendi direito o sentido da notificação?

Em qua., 3 de jan. de 2024 14:08, Guillaume Dalle ***@***.***>
escreveu:

**Comment by gdalle** [comment]
Sorry I tagged the wrong Diogo Netto 🤣

**Comment by Diogo-Netto** [comment]
Sem problemas 😃

Em qua., 3 de jan. de 2024 14:50, Guillaume Dalle ***@***.***>
escreveu:

**Review by d-netto — COMMENTED** [review]
If the goal of `gcscrub` is to ensure all objects reach the oldest generation, then this PR conforms with the changes we introduced in the GC in v1.10.

Want to note that since you are relying on internal GC behavior here (which we're free to change in any version), then it might be a good idea to guard these changes under a version check: i.e. put a `@static if VERSION=1.10` or alike.

**Comment by gdalle** [comment]
@Zentrik wanna add that to make sure that on <= 1.9 we do 4 sweeps and on >= 1.10 we do 3?

**Review by gdalle — APPROVED** [review]

**Pull request merged**
