### PR TITLE
[WIP] Add experimental support for `perf` (via LinuxPerf.jl)

### PR DESCRIPTION
**Pull request by DilumAluthge**
Depends on https://github.com/JuliaPerf/LinuxPerf.jl/pull/32

### CODE REVIEW

**Comment by Zentrik** [comment]
I've rebased and fixed some bugs I encountered here, https://github.com/Zentrik/BenchmarkTools.jl/tree/linux-perf. Is there anything to do to get this merged?

**Comment by DilumAluthge** [comment]
Can you open a new PR? Then I'll close my PR in favor of yours.

**Comment by Zentrik** [comment]
Done

**Comment by DilumAluthge** [comment]
Closing in favor of #347

**Pull request closed without merging**
