### PR TITLE
something closer to new-show-api-compliant?

### PR DESCRIPTION
**Pull request by peterahrens**
I made a rough first pass at making benchmark tools show more things. It sure shows a lot of things now. Maybe this helps with #96?

### CODE REVIEW

**Comment by peterahrens** [comment]
sample output from my test benchmark suite
```
julia> println(IOContext(stdout, :verbose => true), results)
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "matmatmul" => 2-element BenchmarkTools.BenchmarkGroup:
	  tags: []
	  (N = 16, M = 16, K = 16) => 3-element BenchmarkTools.BenchmarkGroup:
		  tags: []
		  "naive" => Trial(5.525 μs)
		  "default" => Trial(1.020 μs)
	  (N = 4, M = 4, K = 4) => 3-element BenchmarkTools.BenchmarkGroup:
		  tags: []
		  "naive" => Trial(179.000 ns)
		  "default" => Trial(243.000 ns)
```

**Comment by jrevels** [comment]
LGTM, thanks!

Are there any places in the docs that need updating before merging this? Seems like there's at least one mention of `showcompact` in there.

**Comment by peterahrens** [comment]
I think that was the only mention of show, so I updated `manual.md`.

**Comment by peterahrens** [comment]
:tada:

**Pull request merged**
